title: Urban Data Tracker
greeting: Welcome to the Urban Data Tracker
description: A lightweight, backend-free tool for tracking urban data coverage by city.
logo: /img/jkan.png
hero_image: /img/homepage-hero.jpg
strict_front_matter: true

# Site theme
jkan_theme: Default

# Dataset schema
schema: default

# Nav bar
navigation:

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  cities:
    output: true
    permalink: /cities/:path/
  datatypes:
    output: true
    permalink: /datatypes/:path/

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: cities
    values:
      layout: city
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      city: Missing
      datatype: Missing
  - scope:
      path: ""
      type: datatypes
    values:
      layout: datatype

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics
google_analytics:
  enabled: false
  code: "UA-XXXXXX-1"

# US Digital Analytics Program - https://analytics.usa.gov
digital_analytics_program:
  enabled: false
  agency: ""
  subagency: ""

# Hypothesis.io - Annotator
hypothesis:
  enabled: false

# Twitter
twittercard:
  enabled: false
  username: "@"

# Open Graph
opengraph:
  enabled: true

# Plugins
plugins:
  - "jekyll-github-metadata"
  - "jekyll-relative-links"
  - "jekyll-paginate-v2"
  - "jekyll-titles-from-headings"

# Exclude these files from the build
exclude:
  - CONTRIBUTING.md
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - scripts/src
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - netlify
  - netlify.toml
  - .parcel-cache
  - docs
